# Generated by Django 3.2.13 on 2022-06-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_budget', '0002_alter_expense_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-amount',)},
        ),
    ]
