# Generated by Django 3.2.13 on 2022-06-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_budget', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='budget',
            field=models.FloatField(),
        ),
    ]
