# Generated by Django 3.2.13 on 2022-06-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_budget', '0004_alter_car_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
