# Generated by Django 3.2.13 on 2022-06-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_budget', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('1', 'Service'), ('2', 'Fuel'), ('3', 'Expense')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
