# Generated by Django 3.2.13 on 2022-06-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_budget', '0007_auto_20220609_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Service', 'Service'), ('Fuel', 'Fuel'), ('Expense', 'Expense')], max_length=10),
        ),
    ]
