# Generated by Django 3.2.13 on 2022-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_budget', '0008_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
