name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        volumes:
          - ./data/db:/var/lib/postgresql/data
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v2
      - name: Build python docker image
        run: docker build . --file Dockerfile --tag python-with-django
      - name: Docker compose django and db environment
        run: docker-compose up -d --build
      - name: Check if django_web is running
        run: docker inspect -f {{.State.Running}} django_web
      - name: Check docker processes
        run: docker ps
      - name: Run django unit tests
        run: docker exec django_web python manage.py test car_budget
