name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build python docker image
        run: docker build . --file Dockerfile --tag python-with-django
      - name: Docker compose django db
        run: docker-compose up -d db
      - name: Docker compose django web
        run: docker-compose up -d web
      - name: Check if django_web is running
        run: docker inspect -f {{.State.Running}} django_web
      - name: Check docker processes
        run: docker ps
      - name: Run django unit tests
        run: docker exec django_web python manage.py test car_budget
