name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Build python docker image
        run: docker build . --file Dockerfile --tag python-with-django
      - name: Docker compose django and db environment
        run: docker-compose up -d --build
      - name: Check if django_web is running
        run: docker inspect -f {{.State.Running}} django_web
      - name: Check docker processes
        run: docker ps
      - name: Run django unit tests
        run: docker exec django_web python manage.py test car_budget
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
